var namespaceMinisat =
[
    [ "RegionAllocator", "da/d2d/classMinisat_1_1RegionAllocator.html", "da/d2d/classMinisat_1_1RegionAllocator" ],
    [ "Heap", "df/d6c/classMinisat_1_1Heap.html", "df/d6c/classMinisat_1_1Heap" ],
    [ "Hash", "dd/d1f/structMinisat_1_1Hash.html", "dd/d1f/structMinisat_1_1Hash" ],
    [ "Equal", "db/d01/structMinisat_1_1Equal.html", "db/d01/structMinisat_1_1Equal" ],
    [ "DeepHash", "d5/d72/structMinisat_1_1DeepHash.html", "d5/d72/structMinisat_1_1DeepHash" ],
    [ "DeepEqual", "dc/d00/structMinisat_1_1DeepEqual.html", "dc/d00/structMinisat_1_1DeepEqual" ],
    [ "Map", "d2/dad/classMinisat_1_1Map.html", "d2/dad/classMinisat_1_1Map" ],
    [ "Option", "dd/df4/classMinisat_1_1Option.html", "dd/df4/classMinisat_1_1Option" ],
    [ "IntRange", "d6/dfb/structMinisat_1_1IntRange.html", "d6/dfb/structMinisat_1_1IntRange" ],
    [ "Int64Range", "d9/d3e/structMinisat_1_1Int64Range.html", "d9/d3e/structMinisat_1_1Int64Range" ],
    [ "DoubleRange", "d2/d13/structMinisat_1_1DoubleRange.html", "d2/d13/structMinisat_1_1DoubleRange" ],
    [ "DoubleOption", "df/de8/classMinisat_1_1DoubleOption.html", "df/de8/classMinisat_1_1DoubleOption" ],
    [ "IntOption", "dc/df0/classMinisat_1_1IntOption.html", "dc/df0/classMinisat_1_1IntOption" ],
    [ "StringOption", "d8/d71/classMinisat_1_1StringOption.html", "d8/d71/classMinisat_1_1StringOption" ],
    [ "BoolOption", "d8/d7d/classMinisat_1_1BoolOption.html", "d8/d7d/classMinisat_1_1BoolOption" ],
    [ "StreamBuffer", "d7/d6a/classMinisat_1_1StreamBuffer.html", "d7/d6a/classMinisat_1_1StreamBuffer" ],
    [ "Queue", "d9/d10/classMinisat_1_1Queue.html", "d9/d10/classMinisat_1_1Queue" ],
    [ "SimpSolver", "db/d9e/classMinisat_1_1SimpSolver.html", "db/d9e/classMinisat_1_1SimpSolver" ],
    [ "Solver", "d5/daf/classMinisat_1_1Solver.html", "d5/daf/classMinisat_1_1Solver" ],
    [ "Lit", "d2/ddd/structMinisat_1_1Lit.html", "d2/ddd/structMinisat_1_1Lit" ],
    [ "lbool", "dc/d5e/classMinisat_1_1lbool.html", "dc/d5e/classMinisat_1_1lbool" ],
    [ "Clause", "db/d09/classMinisat_1_1Clause.html", "db/d09/classMinisat_1_1Clause" ],
    [ "ClauseAllocator", "d4/dd0/classMinisat_1_1ClauseAllocator.html", "d4/dd0/classMinisat_1_1ClauseAllocator" ],
    [ "OccLists", "db/ddc/classMinisat_1_1OccLists.html", "db/ddc/classMinisat_1_1OccLists" ],
    [ "CMap", "de/db5/classMinisat_1_1CMap.html", "de/db5/classMinisat_1_1CMap" ],
    [ "LessThan_default", "dd/d21/structMinisat_1_1LessThan__default.html", "dd/d21/structMinisat_1_1LessThan__default" ],
    [ "vec", "de/dcd/classMinisat_1_1vec.html", "de/dcd/classMinisat_1_1vec" ],
    [ "OutOfMemoryException", "d6/db7/classMinisat_1_1OutOfMemoryException.html", null ]
];